// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tpjwvhznoadsepuhdtux.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRwand2aHpub2Fkc2VwdWhkdHV4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEwMzQ0MjgsImV4cCI6MjA1NjYxMDQyOH0.UvLhEZfcZKfvEroLLilegHJPRQHvm5Xtvg1BvFl1hdo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);